version: "3"
volumes:
  db_data:
services:
  backend:
    build: backend
    ports:
      - 8080:8080
    depends_on: 
        - db
      
  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
        - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_DB: accounting
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
