# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: DSR_summer_project_backend

on:
  push:
    branches:
     -master

jobs:
  build_backend:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
   
    - name: Set application properties
      run: cd backend && sed -i "s/MAIL_USERNAME/${{ secrets.MAIL_USERNAME}}/g; s/MAIL_PASSWORD/${{ secrets.MAIL_PASSWORD }}/g; s/HOST/${{ secrets.MAIL_HOST}}/g; s/PORT/${{ secrets.MAIL_PORT}}/g" src/main/resources/application.properties

    - name: Build with Maven
      run: cd backend && mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml

