# This workflow will build a package using Maven
name: DSR_summer_project_backend

on:
  push:
    branches:
      - master

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set application properties
        run: cd backend && sed -i "s/MAIL_USERNAME/${{ secrets.MAIL_USERNAME}}/g; s/MAIL_PASSWORD/${{ secrets.MAIL_PASSWORD }}/g; s/HOST/${{ secrets.MAIL_HOST}}/g; s/PORT/${{ secrets.MAIL_PORT}}/g" src/main/resources/application.properties

      - name: Build with Maven
        run: cd backend && mvn -B package --file pom.xml
